modules/admin/controllers/ProductsController.php
<?php

namespace app\modules\admin\controllers;

use app\models\BrandsCategories;
use Throwable;
use Yii;
use app\models\Products;
use app\modules\admin\models\search\ProductsSearch;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ProductsController implements the CRUD actions for Products model.
 */
class ProductsController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Products models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ProductsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Products model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Products model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Products();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Products model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }
        $model->file = '/uploads/' . $model->img;
//        echo $model->file;
        $model->attachments = $model->productImages;
        return $this->render('update', [
            'model' => $model,
        ]);
    }
    
    /**
     * Deletes an existing Products model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     * @throws \Exception
     * @throws Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
    
    public function actionBrandsList()
    {
        $request = Yii::$app->request->post('depdrop_parents');
        $brands = BrandsCategories::find()->joinWith('brands')->where(['categories_id' => $request[0]])->all();
        
        $return = [];
        foreach ($brands as $brand) {
            $return[] = [
                'id' => $brand->brands_id,
                'name' => $brand->brands->name,
            ];
        }
        
        return Json::encode(['output' => $return, 'selected' => '']);
    }

    /**
     * Finds the Products model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Products the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Products::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

modules/admin/views/products/_form.php
<?php

use app\models\AddFilter;
use app\models\Categories;
use app\models\MainFilter;
use app\models\ProductParams;
use app\models\Products;
use kartik\depdrop\DepDrop;
use trntv\filekit\widget\Upload;
use unclead\multipleinput\MultipleInput;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use mihaildev\ckeditor\CKEditor;
use mihaildev\elfinder\ElFinder;
use app\models\Brands;

mihaildev\elfinder\Assets::noConflict($this);

/* @var $this yii\web\View */
/* @var $model app\models\Products */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="products-form">
    
    <?php $form = ActiveForm::begin(); ?>
    
    <?= $form->errorSummary($model) ?>
    
    <?= $form->field($model, 'name')->textInput([ 'maxlength' => true ]) ?>
    
    <?php echo $form->field($model, 'slug')
        ->hint(Yii::t('app', 'Если вы оставите это поле пустым, он будет сгенерирован автоматически'))
        ->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'file')->widget(
        Upload::className(),
        [
            'url' => ['/admin/file-storage/upload'],
            'maxFileSize' => 5000000, // 5 MiB


        ]);
    ?>
    
    <?php echo $form->field($model, 'attachments')->widget(
        Upload::className(),
        [
            'url' => ['/admin/file-storage/upload'],
            'sortable' => true,

            'maxFileSize' => 10000000, // 10 MiB
            'maxNumberOfFiles' => 16
        ]);
    ?>
    
    <?= $form->field($model, 'price')->textInput() ?>
    
    <?= $form->field($model, 'discount')->textInput() ?>
    
    <?= $form->field($model, 'short_desc')->textarea([ 'rows' => 6 ]) ?>
    
    <?= $form->field($model, 'content')->widget(CKEditor::className(), [
        'editorOptions' => ElFinder::ckeditorOptions('elfinder', [ 'height' => 300 ]),
    ]); ?>
    
    <?= $form->field($model, 'category_id')->dropDownList(ArrayHelper::map(Categories::find()->all(), 'id', 'name'), [ 'id' => 'category', 'prompt' => 'Выберите категорию продукта' ]) ?>
    
    <?= $form->field($model, 'brand_id')->widget(DepDrop::classname(), [
        'options' => [ 'id' => 'brands' ],
        'data' => ArrayHelper::map(Brands::find()->all(),'id','name'),
        'pluginOptions' => [
            'depends' => [ 'category' ],
            'placeholder' => 'Выберите бренд продукта',
            'url' => Url::to([ 'products/brands-list' ])
        ]
    ]); ?>
    
    <?= $form->field($model, 'status')->checkbox() ?>
    
    <?= $form->field($model, 'meta_keywords')->textInput([ 'maxlength' => true ]) ?>
    
    <?= $form->field($model, 'meta_description')->textInput([ 'maxlength' => true ]) ?>
    
    <?= $form->field($model, 'product_main_filter')->checkboxList(ArrayHelper::map(MainFilter::find()->all(), 'id', 'name')) ?>
    
    <?= $form->field($model, 'product_add_filter')->checkboxList(ArrayHelper::map(AddFilter::find()->where(['not', ['parent_id' => null]])->all(), 'id', 'name'))->label('Выберите допольнительной филтеры') ?>

    <label class="control-label">Вставте главные параметры</label>
    <?php if(!$model->isNewRecord): ?>
        
    <?php endif;?>
    <?= $form->field($model, 'schedule')->widget(MultipleInput::className(), [
        'columns' => [
            [
                'name' => 'product_params',
                'type' => 'dropDownList',
                'items' => ArrayHelper::map(ProductParams::find()->all(), 'id', 'name'),
                'options' => [
                    'prompt' => 'Выберите параметры'
                ]
            ],
            [
                'name' => 'product_params_value',
                'type' => 'textInput',
                'options' => [
                    'placeholder' => 'Значение'
                ],
            ],
            [
                'name' => 'product_main_param',
                'type' => 'checkbox',
                'options' => [
                    'label' => 'Показать на главном'
                ]
            ],
        ],
        'addButtonOptions' => ['class' => 'btn btn-success']
    ])->label(false) ?>
    
    <?= $form->field($model, 'self_params')->widget(MultipleInput::className(), [
        'columns' => [
            [
                'name' => 'product_self_param',
                'options' => [
                    'placeholder' => 'Параметр'
                ]
            ],
            [
                'name' => 'product_self_param_value',
                'options' => [
                    'placeholder' => 'Значение'
                ]
            ],
        ],
        'addButtonOptions' => ['class' => 'btn btn-success']
    ])->label('Вставте Индивидуальные параметры') ?>
    
    <?= $form->field($model, 'related_products')->checkboxList(ArrayHelper::map(Products::find()->all(), 'id', 'name')) ?>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', [ 'class' => 'btn btn-success' ]) ?>
    </div>
    
    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/products/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\search\ProductsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="products-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'img') ?>

    <?= $form->field($model, 'price') ?>

    <?= $form->field($model, 'discount') ?>

    <?php echo $form->field($model, 'slug') ?>

    <?php // echo $form->field($model, 'category_id') ?>

    <?php // echo $form->field($model, 'rating') ?>

    <?php // echo $form->field($model, 'brand_id') ?>

    <?php // echo $form->field($model, 'short_desc') ?>

    <?php // echo $form->field($model, 'main_params_json') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'meta_keywords') ?>

    <?php // echo $form->field($model, 'meta_description') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/products/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Products */

$this->title = 'Создать';
$this->params['breadcrumbs'][] = ['label' => 'Продукты', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="products-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/admin/views/products/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\modules\admin\models\search\ProductsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Продукты';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="products-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Создать продукт', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

//            'id',
            'name',
            [
                'attribute' => 'img',
                'format' => 'html',
                'value' => function ($model) {
                    return Html::img('/uploads/' . $model->img, ['style' => 'max-width: 100px']);
                }
            ],
            [
                'attribute' => 'price',
                'value' =>  function($data) {
                    $price = number_format($data->price, 0, ',', ' ') . ' сум';
                    return $price;
                },
                'format' => 'html',

            ],

//            [
//                'attribute' => 'discount',
//                'value' =>  function($data) {
//                        $price = number_format($data->discount, 0, ',', ' ') . ' сум';
//                        return $data->discount ? $price : 'Не задано';
//                },
//                'format' => 'html',
//
//            ],
            [
                    'attribute' => 'category_id',
                    'value' => function($model){
                        return $model->category->name;
                    }
            ],
            'slug',
            //'content:ntext',

            //'rating',
            //'brand_id',
            //'short_desc:ntext',
            //'main_params_json:ntext',
            //'created_at',
            //'updated_at',
            //'status',
            //'meta_keywords',
            //'meta_description',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

modules/admin/views/products/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Products */

$this->title = 'Изменить продукт: '.$model->name;
$this->params['breadcrumbs'][] = ['label' => 'Продукты', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Изменить';
?>
<div class="products-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/admin/views/products/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Products */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Продукты', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="products-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Создать', ['create', 'id' => $model->id], ['class' => 'btn btn-success']) ?>
        <?= Html::a('Изменить', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Вы действительно хотите удалить продукт '.$model->name.'?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
//            'id',
            'name',
            [
                'attribute' => 'img',
                'format' => 'html',
                'value' => function ($model) {
                    return Html::img('/uploads/' . $model->img, ['style' => 'max-width: 200px']);
                }
            ],
//            'price:currency',
            [
                'attribute' => 'price',
                'value' =>  function($data) {
                    $price = number_format($data->price, 0, ',', ' ') . ' сум';
                    return $price;
                },
                'format' => 'html',

            ],
            [
                'attribute' => 'discount',
                'value' =>  function($model) {
                    if(!empty($model->discount)):
                        $price = number_format($model->discount, 0, ',', ' ') . ' сум';
                        return $price;
                    else:
                        return 'Без скидки';
                    endif;
                },
                'format' => 'html',
            ],
//            'discount',
            [
                    'attribute' => 'content',
                    'format' => 'html',

            ],
            [
                    'attribute' => 'category_id',
                    'value' => $model->category->name,

            ],
//            'category_id',
            'rating',
            [
                'attribute' => 'brand_id',
                'value' => $model->brand->name,

            ],
            'short_desc:ntext',
            [
                    'attribute' => 'main_params_json',
                    'value' => function($model){
                        $return = '';
                        foreach ($model->productsProductParams as $item){
                            $return .= '<b>'.$item->productParams->name. '</b>: '.$item->value . '<br>';
                        }
                        return $return;
                    },
                    'format' => 'html',
            ],
            [
                'attribute' => 'self_params',
                'value' => function($model){
                    $return = '';
                    foreach ($model->productSelfParams as $item){
                        $return .= '<b>'.$item->name. '</b>: '.$item->value . '<br>';
                    }
                    return $return;
                },
                'format' => 'html',
            ],
//
            //'self_params',
            'created_at',
            'updated_at',
            [
                'attribute' => 'status',
                'value' => function($model)
                {
                    return $model->status == 1 ? 'Опубликовоно' : 'Не опубликовоно';
                }
            ],
            'meta_keywords',
            'meta_description',
        ],
    ]) ?>

</div>